### ISSUE TITLE
FTP-Deploy-Action always fail, can we Github Pages instead?

### ISSUE THREAD

**Issue by longfangsong** [tikv/client-rust#212]
FTP-Deploy-Action always fail, can we Github Pages instead?
eg.
```yaml
name: Build and deploy doc

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build doc
      run: cargo doc --release --document-private-items
    - name: Deploy docs
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: target/doc
        CLEAN: true
```
