### ISSUE TITLE
Client failed to connect 

### ISSUE THREAD

**Issue by florianeichin** [tikv/client-rust#34]
I try to use the client to connect to a tikv running in docker-compose and getting the following error. 
`/home/user/.cargo/git/checkouts/client-rust-5a1ccd35a54db20f/3ab4f95/src/rpc/pd/leader.rs:433]: failed to connect to [name: "pd0" member_id: 2569432990168970607 peer_urls: "http://pd0:2380" client_urls: "http://pd0:2379"] }`

I don't exactly know if it's a bug or just wrong usage.
Am I missing anything?

Client Code
```
use futures::Future;
use tikv_client::{raw::Client, Config};
fn main() {
    let config = Config::new(vec!["172.18.02:2379"]);
    let connect = Client::new(config);
    let client =  connect.wait().unwrap() 
    let key = "a";
    let val = "b";
    let req = client.put(key, val).wait();
}
```

Docker Compose File
```
version: '2.1'

services:
  pd0:
    image: pingcap/pd:latest
    ports:
      - "2379"
    command:
      - --name=pd0
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd0:2379
      - --advertise-peer-urls=http://pd0:2380
      - --initial-cluster=pd0=http://pd0:2380
    restart: on-failure
  
  tikv0:
    image: pingcap/tikv:latest
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv0:20160
      - --data-dir=/data/tikv0
      - --pd=pd0:2379

    depends_on:
      - "pd0"
    restart: on-failure
```
