### ISSUE TITLE
blocker: Remove All git patches of crate

### ISSUE THREAD

**Issue by Xuanwo** [tikv/client-rust#397]
We have three git patched deps here:

```toml
[patch.crates-io]
raft-proto = { git = "https://github.com/tikv/raft-rs", rev="95c532612ee6a83591fce9a8b51d6afe87b58835"}
protobuf-codegen = { git = "https://github.com/pingcap/rust-protobuf", rev="82b49fea7e696fd647b5aca0a6c6ec944eab3189" }
protobuf = { git = "https://github.com/pingcap/rust-protobuf", rev="82b49fea7e696fd647b5aca0a6c6ec944eab3189" }
```

This will block us to upload the new version of crates. We should remove them and depend on tagged version instead.
